// Code generated by protoc-gen-go. DO NOT EDIT.
// source: isi_saldo.proto

package isi_saldo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IsiSaldoData struct {
	IdIsiSaldo           int64    `protobuf:"varint,1,opt,name=id_isi_saldo,json=idIsiSaldo,proto3" json:"id_isi_saldo,omitempty"`
	IdPenguna            string   `protobuf:"bytes,2,opt,name=id_penguna,json=idPenguna,proto3" json:"id_penguna,omitempty"`
	NominalIsiSaldo      float32  `protobuf:"fixed32,3,opt,name=nominal_isi_saldo,json=nominalIsiSaldo,proto3" json:"nominal_isi_saldo,omitempty"`
	WaktuIsiSaldo        string   `protobuf:"bytes,4,opt,name=waktu_isi_saldo,json=waktuIsiSaldo,proto3" json:"waktu_isi_saldo,omitempty"`
	ErrorsMessage        []string `protobuf:"bytes,5,rep,name=errors_message,json=errorsMessage,proto3" json:"errors_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsiSaldoData) Reset()         { *m = IsiSaldoData{} }
func (m *IsiSaldoData) String() string { return proto.CompactTextString(m) }
func (*IsiSaldoData) ProtoMessage()    {}
func (*IsiSaldoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f97791809ce604f, []int{0}
}

func (m *IsiSaldoData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsiSaldoData.Unmarshal(m, b)
}
func (m *IsiSaldoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsiSaldoData.Marshal(b, m, deterministic)
}
func (m *IsiSaldoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsiSaldoData.Merge(m, src)
}
func (m *IsiSaldoData) XXX_Size() int {
	return xxx_messageInfo_IsiSaldoData.Size(m)
}
func (m *IsiSaldoData) XXX_DiscardUnknown() {
	xxx_messageInfo_IsiSaldoData.DiscardUnknown(m)
}

var xxx_messageInfo_IsiSaldoData proto.InternalMessageInfo

func (m *IsiSaldoData) GetIdIsiSaldo() int64 {
	if m != nil {
		return m.IdIsiSaldo
	}
	return 0
}

func (m *IsiSaldoData) GetIdPenguna() string {
	if m != nil {
		return m.IdPenguna
	}
	return ""
}

func (m *IsiSaldoData) GetNominalIsiSaldo() float32 {
	if m != nil {
		return m.NominalIsiSaldo
	}
	return 0
}

func (m *IsiSaldoData) GetWaktuIsiSaldo() string {
	if m != nil {
		return m.WaktuIsiSaldo
	}
	return ""
}

func (m *IsiSaldoData) GetErrorsMessage() []string {
	if m != nil {
		return m.ErrorsMessage
	}
	return nil
}

func init() {
	proto.RegisterType((*IsiSaldoData)(nil), "isi_saldo.isiSaldoData")
}

func init() { proto.RegisterFile("isi_saldo.proto", fileDescriptor_9f97791809ce604f) }

var fileDescriptor_9f97791809ce604f = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x2c, 0xce, 0x8c,
	0x2f, 0x4e, 0xcc, 0x49, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x9d, 0x62, 0xe4, 0xe2, 0xc9, 0x2c, 0xce, 0x0c, 0x06, 0x71, 0x5c, 0x12, 0x4b, 0x12, 0x85, 0x14,
	0xb8, 0x78, 0x32, 0x53, 0xe2, 0xe1, 0x0a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0xb8, 0x32,
	0x53, 0x3c, 0xa1, 0xaa, 0x84, 0x64, 0xb9, 0xb8, 0x32, 0x53, 0xe2, 0x0b, 0x52, 0xf3, 0xd2, 0x4b,
	0xf3, 0x12, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x38, 0x33, 0x53, 0x02, 0x20, 0x02, 0x42,
	0x5a, 0x5c, 0x82, 0x79, 0xf9, 0xb9, 0x99, 0x79, 0x89, 0x39, 0x48, 0xa6, 0x30, 0x2b, 0x30, 0x6a,
	0x30, 0x05, 0xf1, 0x43, 0x25, 0xe0, 0x46, 0xa9, 0x71, 0xf1, 0x97, 0x27, 0x66, 0x97, 0x94, 0x22,
	0xa9, 0x64, 0x01, 0x9b, 0xc7, 0x0b, 0x16, 0x86, 0xab, 0x53, 0xe5, 0xe2, 0x4b, 0x2d, 0x2a, 0xca,
	0x2f, 0x2a, 0x8e, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x55, 0x60, 0x06, 0x29,
	0x83, 0x88, 0xfa, 0x42, 0x04, 0x8d, 0x02, 0xc1, 0x5e, 0x05, 0x6b, 0x09, 0x4e, 0x2d, 0x2a, 0xcb,
	0x4c, 0x4e, 0x15, 0xb2, 0xe3, 0xe2, 0x80, 0x09, 0x09, 0x89, 0xeb, 0x21, 0x02, 0x02, 0xd9, 0xcf,
	0x52, 0xb8, 0x24, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x21, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x63, 0xb0, 0xa6, 0x4a, 0x44, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IsiSaldoServiceClient is the client API for IsiSaldoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IsiSaldoServiceClient interface {
	IsiSaldo(ctx context.Context, in *IsiSaldoData, opts ...grpc.CallOption) (*IsiSaldoData, error)
}

type isiSaldoServiceClient struct {
	cc *grpc.ClientConn
}

func NewIsiSaldoServiceClient(cc *grpc.ClientConn) IsiSaldoServiceClient {
	return &isiSaldoServiceClient{cc}
}

func (c *isiSaldoServiceClient) IsiSaldo(ctx context.Context, in *IsiSaldoData, opts ...grpc.CallOption) (*IsiSaldoData, error) {
	out := new(IsiSaldoData)
	err := c.cc.Invoke(ctx, "/isi_saldo.isiSaldoService/isiSaldo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IsiSaldoServiceServer is the server API for IsiSaldoService service.
type IsiSaldoServiceServer interface {
	IsiSaldo(context.Context, *IsiSaldoData) (*IsiSaldoData, error)
}

func RegisterIsiSaldoServiceServer(s *grpc.Server, srv IsiSaldoServiceServer) {
	s.RegisterService(&_IsiSaldoService_serviceDesc, srv)
}

func _IsiSaldoService_IsiSaldo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsiSaldoData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsiSaldoServiceServer).IsiSaldo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isi_saldo.isiSaldoService/IsiSaldo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsiSaldoServiceServer).IsiSaldo(ctx, req.(*IsiSaldoData))
	}
	return interceptor(ctx, in, info, handler)
}

var _IsiSaldoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "isi_saldo.isiSaldoService",
	HandlerType: (*IsiSaldoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "isiSaldo",
			Handler:    _IsiSaldoService_IsiSaldo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "isi_saldo.proto",
}
